Blackboard.Web/Models/ErrorViewModel.cs
using System;

namespace Blackboard.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Blackboard.Web/Models/MessageViewModel.cs
using System;

namespace Blackboard.Web.Models
{
    public class MessageViewModel
    {
        public ulong ID { get; set; }
        public string Text { get; set; }
        public DateTime CreationTime { get; set; }

        public MessageViewModel()
        { 
        }

        public MessageViewModel(ulong id, string text, DateTime creationTime)
        {
            ID = id;
            Text = text;
            CreationTime = creationTime;
        }
    }
}

Blackboard.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Blackboard.Web.Models;
using Microsoft.AspNetCore.Http;
using Blackboard.Core.Boundaries;
using Blackboard.Core.Factory;
using BlackBoard.Web.Repository;
using Blackboard.Core.UseCases.GetAllMessage;

namespace Blackboard.Web.Controllers
{
    public class HomeController : Controller
    {
        public HomeController(ICoreFactory factory) : base()
        {
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Blackboard.Web/Controllers/MessageController.cs
using Blackboard.Core.Boundaries;
using Blackboard.Core.Factory;
using Blackboard.Core.UseCases;
using Blackboard.Core.UseCases.DetachMessage;
using Blackboard.Core.UseCases.GetAllMessage;
using Blackboard.Core.UseCases.GetMessageByID;
using Blackboard.Core.UseCases.PublishMessage;
using Blackboard.Web.Models;
using Blackboard.Web.Presenters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;


namespace Blackboard.Web.Controllers
{
    public class MessageController : Controller
    {
        private readonly SingleMessagePresenter messagePresenter;
        private readonly MultipleMessagePresenter messagesPresenter;
        private readonly MessageDetachingPresenter messageDetachingPresenter;

        private readonly IInputBoundary<GetAllMessagesRequest, GetAllMessagesResponse> getAllMessagesUseCase;
        private readonly IInputBoundary<GetMessageByIDRequest, IGetMessageResponse> getMessageByIDUseCase;
        private readonly IInputBoundary<DetachMessageRequest, IDetachMessageResponse> detachMessageUseCase;


        public MessageController(ICoreFactory factory) : base()
        {
            messagePresenter = new SingleMessagePresenter();
            messagesPresenter = new MultipleMessagePresenter();
            messageDetachingPresenter = new MessageDetachingPresenter();

            getAllMessagesUseCase = factory.Build(messagesPresenter);
            getMessageByIDUseCase = factory.Build(messagePresenter);
            detachMessageUseCase = factory.Build(messageDetachingPresenter);
        }

        // GET: Message
        public IActionResult Index()
        {
            getAllMessagesUseCase.Execute(new GetAllMessagesRequest());
            return View(messagesPresenter.GetMessageViewModels());
        }

        // GET: Message/Delete/5
        public ActionResult Delete(ulong id)
        {
            getMessageByIDUseCase.Execute(new GetMessageByIDRequest() { ID = id });
            var messageViewModel = messagePresenter.GetMessageViewModel();
            if (messageViewModel != null)
                return View(messageViewModel);

            return RedirectToAction(nameof(Index));
        }

        // POST: Message/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(ulong id, IFormCollection collection)
        {
            try
            {
                detachMessageUseCase.Execute(new DetachMessageRequest() { ID = id });
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        } 
    }
}

Blackboard.Web/Controllers/PublishingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blackboard.Core.Boundaries;
using Blackboard.Core.Factory;
using Blackboard.Core.UseCases.PublishMessage;
using Blackboard.Web.Presenters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Blackboard.Web.Controllers
{
    public class PublishingController : Controller
    {
        private readonly IInputBoundary<PublishMessagesRequest, IPublishMessagesResponse> publishMessageUseCase;
        private readonly MessagePublishingPresenter presenter;


        public PublishingController(ICoreFactory factory)
        {
            presenter = new MessagePublishingPresenter();
            publishMessageUseCase = factory.Build(presenter);
        }
        // GET: Message/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Message/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            var text = collection["Text"];
            publishMessageUseCase.Execute(new PublishMessagesRequest() { Text = text });

            if (presenter.LastMessageWasSuccessfullyCreated)
                return RedirectToAction("Index", "Message");
            else
                return View();
        }
    }
}

Blackboard.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Blackboard.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

Blackboard.Web/Views/Message/Index.cshtml
@model IEnumerable<MessageViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<h1>@ViewData["Title"]</h1>
<meta http-equiv="refresh" content="20">
<table class="table" id="messages">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.First().CreationTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.First().Text)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var message in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => message.CreationTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => message.Text)
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@message.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Blackboard.Web/Views/Shared/Create.cshtml
@model Blackboard.Web.Models.MessageViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>MessageModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Blackboard.Web/Views/Shared/Delete.cshtml
@model Blackboard.Web.Models.MessageViewModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MessageModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreationTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreationTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Blackboard.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blackboard.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Message" asp-action="Index" class="navbar-brand">Blackboard.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Message" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Publishing" asp-action="Create">Create</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Blackboard.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>